name: binder-environment
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - git+https://github.com/morphomatics/morphomatics.git@acf6295  
    - pyvista
    - trame
    - matplotlib
    - scikit-learn
